[[redirects]]
  from = "/api/*"  # 프론트엔드에서 "/api"로 시작하는 모든 요청을 처리
  to = "http://13.124.80.0:80/api/:splat"  # HTTP API 서버로 요청을 프록시 처리
  status = 200  # 성공 상태 코드로 응답
  force = true  # Netlify에서 강제로 HTTPS를 적용하도록 설정